### ISSUE TITLE
Perte de l'item en main lorsque blessé et à cheval

### ISSUE THREAD

**Issue by Itheniel** [dremixam/rouillerp#25]
Cela fait deux fois que je me fais blessé à cheval lors de chasse. A chaque fois j'ai perdu l'item que j'avais en main (2 arc dans ce cas précis)

Pour le recréer c'est simple: monte sur un cheval avec qqch dans les main et va te faire blessé. Garanti avec les animaux, reste à voir avec un joueur ou autre.

**Comment by dremixam** [comment]
Par blessé tu veux dire l'état blessé ? Genre avec l'écran de blessure tout ca ? Si c'est le cas c'est le comportement normal du jeu et la bizarrerie est plutot que ca ne le fasse que quand on est a cheval
