### ISSUE TITLE
Mort non instantanée

### ISSUE THREAD

**Issue by Elkann** [dremixam/rouillerp#3]
Aujourd'hui, vers 20h (heure sans importance)

En faisant F1 -> kill, si le personnage n'est pas déjà à terre, il tombe juste à terre blessé.
Il n'est pas possible de refaire un "kill" avant un certain moment.

Je pense qu'il faudrait enlever ce cooldown afin de permettre aux joueurs de se suicider rapidement

**Comment by dremixam** [comment]
C'est le fonctionnement normal attendu
