### ISSUE TITLE
Bug vocal a la communauté 

### ISSUE THREAD

**Issue by Nardoux** [dremixam/rouillerp#45]
J'ai un bug courant quand je me trouve a la commu, de manière totalement aléatoire je n'entends plus personne et l'affichage de la notion "chuchoter, crier et parler" bug, sois elle arrête d'apparaitre, sois elle reste en permanence sur mon écran. 
Il suffit que je déco reco du serv pour que ça revienne, mais ça reste chiant

**Comment by dremixam** [comment]
Est-ce que tu as une heure exacte et une date d'un moment où ça t'est
arrivé ?

**Comment by Nardoux** [comment]
Mercredi 14/04 a 15h00/15h10, ça viens de me le faire dans cette tranche horaire, au moment dans rentrer dans la commu
Petit edit : ça viens de ce reproduire entre 15h20/15h25 : je passer devant l'atelier a la commu, comme dab l'affichage pour savoir si je cri etc est bugué, même si cette fois il a fini par revenir a la normal, il était très très décaler.
J'ai malheureusement personne autour pour savoir si j'entends les gens ou non

**Comment by Nardoux** [comment]
Yep, le problème empire de plus en plus, je pense que c'est lié au chargement de la communauté, maintenant en plus de ne plus entendre personne, j'ai l'inventaire qui réponds très très très lentement (30/40s de retard) et je ne vois plus les portes s'ouvrir, avec généralement de gros roll back en véhicule dans la commu, ce soucis ne m'arrive nul part ailleurs.

**Comment by dremixam** [comment]
Est-ce que le problème est toujours d'actualité ?

**Comment by Nardoux** [comment]
Un peu, mais je pense que c'est rust qui a énormément de mal, et que c'est
lié au chargement des panneaux, tableaux etc, vu que, une fois les panneaux
désactiver, je n'avais plus du tout le problème, du coup j'ai juste réduit
l'affichage des panneaux à 20 et ça a l'air d'être jouable (même si c'est
toujours un poil la galère vers le port de la commu, j'ai plus besoin de
deco reco)

**Comment by dremixam** [comment]
Si tu as au moins 16Go de ram met la distance d'affichage a fond tout en laissant réduit l'affichage des panneaux ça devrait limiter les échanges avec le serveur
