### ISSUE TITLE
Saut pour sortir du cheval +60hp to Wounded

### ISSUE THREAD

**Issue by rayulRP** [dremixam/rouillerp#48]
ce soir vers 21h30, en sortant de mon cheval sur la place de la communauté
j'ai fais un saut et je suis direct tombé Wounded
j'avais bien +60hp
j'ai eu l'impression que le cheval a fait une animation qui m'aurait poussé
1x que cela m'arrive alors que je descends +100x par jour du cheval
je n'ai pas reproduis le phénomène

**Comment by dremixam** [comment]
Beaucoup trop rare comme bug, on interviendra quand des gens l'auront
