### ISSUE TITLE
Armes qui one shoot sans passé par la case "blessé"

### ISSUE THREAD

**Issue by Nardoux** [dremixam/rouillerp#5]
Bon, aprés moult test, on sait pas comment ça arrive, mais c'est arriver avec : le L96, Le spas12, le pipe shotgun et l'arc composite, 
dans chaque cas c'est un headshoot qui causer le soucis, mais même en reconstituant la situation, avec les même armes et munitions, le headshoot ne tuer pas (on a pas réussi a le reproduire sauf pour l'arc composite qui a eu lieu dans nos test, mais ne one shooter plus après)

**Comment by dremixam** [comment]
Oui je suis dessus

**Comment by dremixam** [comment]
Corrigé
