### ISSUE TITLE
Deco reco qui tue

### ISSUE THREAD

**Issue by Nardoux** [dremixam/rouillerp#6]
Je me suis deco hier soir dans un endroits 100% safe, mais quand je me suis reco le jeu m'as mis comme quoi j'étais mort, tuer par un joueur endormi lui aussi depuis hier.
je viens de deco en vie au même endroit après le restart du serveur vers 18h50, et je suis de nouveau mort de la même manière, par ce même joueur toujours déco.
Aprés respawn mon cadavre avait disparu dans les deux cas, aucun sac ou loot sur le sol, mon stuff est perdu a jamais 

![Mort](https://user-images.githubusercontent.com/78881982/107677654-cd4bea80-6c9a-11eb-8c21-727e8e492d47.PNG)

**Comment by dremixam** [comment]
Corrigé
