### ISSUE TITLE
Statut blessé qui se résorbe tout seul

### ISSUE THREAD

**Issue by dremixam** [dremixam/rouillerp#7]
Certains joueurs parviennent à se relever sans aide exterieure.

Visiblement appuyer sur echap lorsqu'on est a terre peut provoquer un bug où l'écran de blessure reste affiché

**Comment by dremixam** [comment]
Si vous êtes bloqué avec l'écran blessé qui ne s'enleve pas, une déco/reco devrait régler le problème

**Comment by itsmeAnRa** [comment]
En tant que membre de La Communauté, je me suis déjà retrouvé face à ce bug après une chute, pour le reproduire j'ai du : 
- Être mis à terre
- Demander de l'aide.
- Aucun medic n'avait été dispo, avoir l'option pour demander de l'aide externe.
- Cliquer sur "Non".
- L'écran de blessure est passé en Vanilla, puis après un certain temps, mon personnage s'est relevé tout seul.

**Comment by itsmeAnRa** [comment]
Je viens de reproduire le bug : 
Je suis tombé de chute chez moi (donc avec le confort) je n'ai touché à rien et je me suis relevé tout seul mais l'écran de mort persistait. En me déconnectant reconnectant, le message est réapparu.

**Comment by dremixam** [comment]
> Je viens de reproduire le bug :
> Je suis tombé de chute chez moi (donc avec le confort) je n'ai touché à rien et je me suis relevé tout seul mais l'écran de mort persistait. En me déconnectant reconnectant, le bug est réapparu.

Intéressant ça, à creuser

**Comment by dremixam** [comment]
Surtout que normalement il devrait pas y avoir de confort chez les gens

**Comment by itsmeAnRa** [comment]
Avec la reconnexion je reste bien au sol cette fois-ci
